name: Flutter CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.22.0"

    - name: Flutter pub get
      run: flutter pub get

    - name: Analyze
      run: flutter analyze

    - name: Build APK
      run: flutter build apk --release
