name: Worker CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "worker/**"

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Build Worker
      working-directory: worker
      run: wrangler build

    # Uncomment to auto-publish
    # - name: Publish Worker
    #   working
